### ISSUE TITLE
Error when changing Zone

### ISSUE THREAD

**Issue by ben1328** [kaminaris/KeystoneManager#1]
Message: ...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:296: LibDBIcon-1.0: Object 'KeystoneManager' is already registered.
Time: Tue Sep 18 10:44:28 2018
Count: 1
Stack: ...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:296: LibDBIcon-1.0: Object 'KeystoneManager' is already registered.
(tail call): ?
[C]: in function `error'
...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:296: in function `Register'
Interface\AddOns\KeystoneManager\main.lua:165: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by pwilkowski** [comment]
Fixed in 8.0.2.
