### ISSUE TITLE
CN Reset Time Support

### ISSUE THREAD

**Issue by LiangYuxuan** [kaminaris/KeystoneManager#11]
Hi, here is the reset time of CN Realm in unix timestamp.

```lua
local cnResetTime = 1500505200 -- CN Thursday at reset
```

Could you add support for CN Realm? Thank you very much!

**Comment by pwilkowski** [comment]
Done in version 8.1.5 please check if it works

**Comment by LiangYuxuan** [comment]
It works perfectly. Thank you!
