### ISSUE TITLE
Displaying wrong weekly highest key completed.

### ISSUE THREAD

**Issue by ben1328** [kaminaris/KeystoneManager#2]
Keystone Manager is displaying that i've done a +10 this week on my druid but I've only done a +4.

I did complete a +10 before reset which gave the + 9 shrine keystone this week.

![weekly](https://user-images.githubusercontent.com/43359924/45659086-04ebf200-bb36-11e8-9858-1f893381b8be.png)

**Comment by Caldaren** [comment]
It seems to be grabbing seasonal best.
My 3 characters have differenbt levels of highest seasonal, and it grabs that for each.

**Comment by pwilkowski** [comment]
Fixed in 8.0.2, yeah it was it. Season best not weekly, now it works properly.
