### ISSUE TITLE
Bad Argument #1 to pairs

### ISSUE THREAD

**Issue by Caldaren** [kaminaris/KeystoneManager#3]
![image](https://user-images.githubusercontent.com/43402566/46342457-13103700-c63b-11e8-88d2-a33a2692a5b8.png)

**Comment by pwilkowski** [comment]
How did you get this? When?

**Comment by Caldaren** [comment]
I get this whenever I change character, location independant as far as I can tell, I haven't had the time to really look into it yet.

**Comment by pwilkowski** [comment]
looks like corrupted database, can you try clicking Reset?

**Comment by Caldaren** [comment]
Not quite sure where I would click reset, but I deleted settings + reinstalled in twitch client and it still happens.

**Comment by pwilkowski** [comment]
should be fixed in 8.0.3
