### ISSUE TITLE
KeystoneManager lua errors

### ISSUE THREAD

**Issue by jglatchney** [kaminaris/KeystoneManager#4]
Date: 2018-10-18 17:29:57
ID: 5
Error occured in: Global
Count: 306
Message: ..\AddOns\KeystoneManager\main.lua line 425:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [C]: pairs()
   KeystoneManager\main.lua:425: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:
      Ace3\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  Ace3, v
  AckisRecipeList, v7.3.0.1
  AckisRecipeListQuickScan, v7.3.0.1
  ACP, vr259 
  AdvancedInterfaceOptions, v1.2.8
  Altoholic, vr190
  Atlas, vv1.44.03
  AtlasArena, vv1.07.02
  AtlasBattlegrounds, vv1.44.00
  AtlasBurningCrusade, vv1.44.00
  AtlasCataclysm, vv1.44.00
  AtlasClassicWoW, vv1.44.00
  AtlasClassOrderHalls, vv1.44.00
  AtlasDungeonLocs, vv1.44.00
  AtlasLegion, vv1.44.00
  AtlasMistsofPandaria, vv1.44.00
  AtlasOutdoorRaids, vv1.44.00
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.44.00
  AtlasWarlordsofDraenor, vv1.44.00
  AtlasWorldEvents, vv3.24
  AtlasWrathoftheLichKing, vv1.44.00
  AtlasLoot, vv8.08.01
  AtlasLootBattleforAzeroth, vv8.08.01
  AtlasLootBurningCrusade, vv8.08.01
  AtlasLootCataclysm, vv8.08.01
  AtlasLootClasses, vv3.1
  AtlasLootClassic, vv8.08.01
  AtlasLootLegion, vv8.08.01
  AtlasLootMistsofPandaria, vv8.08.01
  AtlasLootSource, vv0.3
  AtlasLootWarlordsofDraenor, vv8.08.01
  AtlasLootWrathoftheLichKing, vv8.08.01
  AtlasMajorCitiesEnhanced, vv1.16
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  auccheapsearcher, v20180721
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  AutoTurnIn, v7.0.9
  BarrelsOEasy, v1.1.11
  BattlePetBreedID, vr179
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  CanIMogIt, v8.0.0v1.13
  CollectionShop, v3.06
  CurrencySorter, v
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.0.13
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPVEM, v8.0.4
  DejaCharacterStats, v800r103
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  FishingBuddy, v1.9.19
  GarrisonCommanderBroker, v3.0.0 1.1.0
  GnomeSequencer, v7.3.0.1
  Grail, v097
  GrailQuestsenUS, v27178
  HandyNotes, vv1.5.3
  HandyNotesArgus, vv0.10
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.29
  HandyNotesCamelFigurines, v1.3
  HandyNotesDraenorTreasures, v1.21
  HandyNotesHigherDimensionalLearning, v1
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesKosumoth, v1
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesLunarFestival, vv1.5
  HandyNotesSpecialNPCsEtc, v1.1.1-Beta
  HandyNotesSummerFestival, vv1.5
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleChests, v1.20
  HandyNotesTimelessTreasures, v1.0.7
  HealBot, v8.0.1.0
  HiddenArtifactTracker, v
  Informant, v8.0.6159 (SwimmingSeadragon)
  KeystoneManager, v8.0.2
  LibSharedMedia30, v3.0-104
  MacroToolkit, vv7.3.0.2
  MacroToolkitIcons, v7.2.0.0
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.149
  MinimalArchaeology, v8.0.12.1
  NPCScan, v8.0.1.13
  OmniCC, v8.0.9
  Outfitter, v5.20.3
  Overachiever, v1.0.4
  OverachieverCache, v1.0.4
  OverachieverTrade, v1.0.4
  Paste, v1.4.10
  PersonalLootHelper, v2.17
  PetBattleTeams, v3.3.10
  PetTracker, v8.0.6
  PetTrackerBreeds, v8.0.6
  PetTrackerSwitcher, v8.0.6
  PetTrackerUpgrades, v8.0.6
  PremadeAutoAccept, v1.0.1
  RSA, vr508-Release
  RSADruid, v
  SavedInstances, v8.0.6
  SellJunk, v3.0.16
  SharedMedia, v3.1.0-191
  SharedMediaAdditionalFonts, v1.0.26
  SharedMediaAdditionalSounds, v7.0
  SilentWorldQuestOptions, v8.0.1
  SilverDragon, vv4.0.13
  SilverDragonBattleForAzeroth, vv4.0.13
  SilverDragonBurningCrusade, vv4.0.13
  SilverDragonCataclysm, vv4.0.13
  SilverDragonLegion, vv4.0.13
  SilverDragonMists, vv4.0.13
  SilverDragonVanilla, vv4.0.13
  SilverDragonWarlords, vv4.0.13
  SilverDragonWrath, vv4.0.13
  Stubby, v8.0.6161 (SwimmingSeadragon)
  Titan, v5.14.12.80000
  TitanBag, v5.14.12.80000
  TitanClock, v5.14.12.80000
  TitanGold, v5.14.12.80000
  TitanLocation, v5.14.12.80000
  TitanLootType, v5.14.12.80000
  TitanPerformance, v5.14.12.80000
  TitanRepair, v5.14.12.80000
  TitanVolume, v5.14.12.80000
  TitanXP, v5.14.12.80000
  TomTom, vv80001-1.0.2
  TradeSkillInfo, vv2.4.1
  TransmogShop, v2.01
  WorldQuestTracker, v
  xanMortarPestle, v3.2
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=1305)

**Comment by pwilkowski** [comment]
Should have been fixed in recent release
