### ISSUE TITLE
ER: Slash command to post all available keys to current report target

### ISSUE THREAD

**Issue by jury** [kaminaris/KeystoneManager#6]
Hi there,

First time caller, long time user!

This is just a simple enhancement request that it would be awesome if there was a slashcommand for reporting your current keys to the currently configured reporting destination.

Something like:

/keyshare

**Comment by pwilkowski** [comment]
resolved in 8.0.8

command is /keyreport

**Comment by jury** [comment]
Thanks for the super fast improvements!
