### ISSUE TITLE
"Excludes" not defined in latest update

### ISSUE THREAD

**Issue by jury** [kaminaris/KeystoneManager#7]
Getting the following error when logging in on 8.0.7 version. Looks like the self.db.excludes isn't initialized anywhere.

Date: 2018-12-23 13:56:53
ID: 1
Error occured in: Global
Count: 3
Message: ..\AddOns\KeystoneManager\main.lua line 723:
   attempt to index field 'excludes' (a nil value)
Debug:
   KeystoneManager\main.lua:723: GetKeystoneColor()
   KeystoneManager\main.lua:718: GetShortInfo()
   KeystoneManager\main.lua:697: RefreshDataText()
   KeystoneManager\main.lua:570: ?()
   ...ACU\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...ACU\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...ACU\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   ...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  ACU, v
  AdvancedInterfaceOptions, v1.2.9
  AngryKeystones, v
  AngryWorldQuests, v
  AskMrRobot, v69
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  AutoBar, v8.0.0.06
  AutoLog, vv8.0.1.2
  AverageItemLevel, v8.0.0.3
  BagBrother, v
  Bagnon, v8.0.7
  BagnonItemLevel, v1.0
  BagnonScrap, v21
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BlizzMove, vv1.8
  BloodTrader, v2.2
  CanIMogIt, v8.0.0v1.13
  Clique, vv80000-1.0.0
  ColorPickerPlus, v
  DBMCore, v8.1.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r118
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.84
  ElvUIBenikUI, v3.52
  ElvUIVisualAuraTimers, v1.56
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  ExpeditionAssistant, v8.0.0.6
  FBBroker, v1.34.10
  FBOutfitDisplayFrame, v1.9.2
  FBTrackingFrame, v1.9
  FishingBuddy, v1.9.24
  GatherMate2, v1.43.4
  GTFO, v4.46.12
  HandyNotes, vv1.5.3
  HandyNotesAchievements, v0.4.22
  HandyNotesArgus, vv0.12
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBFAHFTracker, v8.0.5
  HandyNotesBrokenShore, vv1.30
  HandyNotesDirections, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.45
  HandyNotesLegionInstanceWorldQuests, vv1.17
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesTimelessIsleChests, v1.21
  HandyNotesWarfrontRares, v0.5.0
  HereBeDragons, v2.00-release
  HereBeDragons10, v2.00-release
  Informant, v8.0.6159 (SwimmingSeadragon)
  KeystoneHelper, v8.0.0.1
  KeystoneManager, v8.0.7
  MacroToolkit, vv7.3.0.2
  MacroToolkitIcons, v7.2.0.0
  Masque, v8.0.1
  MasqueElvUIesque, v1.0
  MikScrollingBattleText, v5.7.149
  MoveAnything, v17.0.2
  NiceBubbles, v1.0
  NPCScan, v8.0.1.13
  Pawn, v2.2.32
  PersonalLootHelper, v2.19
  PetLeash, v3.1.5
  PremadeGroupsFilter, v1.24
  RaiderIO, v8.0.1 (v201812230600)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  RelicInspector, v3.0
  Routes, vv1.6.0
  Scrap, v13.12
  Stubby, v8.0.6161 (SwimmingSeadragon)
  SubSpec, v2.2.0.1
  Titan, v5.15.2.80100
  TitanBag, v5.15.2.80100
  TitanChallengeModes, v0.3.1
  TitanClock, v5.15.2.80100
  TitanCurrency, v8.1
  TitanGold, v5.15.2.80100
  TitanLocation, v5.15.2.80100
  TitanLootType, v5.15.2.80100
  TitanPerformance, v5.15.2.80100
  TitanPoints, v8.0.1
  TitanRepair, v5.15.2.80100
  TitanVolume, v5.15.2.80100
  TitanXP, v5.15.2.80100
  TomTom, vv80001-1.0.2
  TransmogTokens, v1.4.9
  WeakAuras, v2.10.11
  wMarker, v2.5.5
  WowLua, vv80000-1.0.0
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=d5d)

**Comment by pwilkowski** [comment]
fixed in 8.0.8

**Comment by jury** [comment]
Thanks for the super fast fix!
